version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: employee-attendance-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:password@db:5432/attendance_db
      - JWT_SECRET_KEY=supersecretkey
      - BACKEND_CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: employee-attendance-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: employee-attendance-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
